/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AdminAboutRouteImport } from './routes/admin/about'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminHomeRouteImport } from './routes/admin/home'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPhotographsRouteImport } from './routes/admin/photographs'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSetPasswordRouteImport } from './routes/admin/set-password'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiTrackViewRouteImport } from './routes/api/track-view'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DevelopmentsIndexRouteImport } from './routes/developments/index'
import { Route as DevelopmentsSplatRouteImport } from './routes/developments/$'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogCategoriesRouteImport } from './routes/admin/blog/categories'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as AdminPreviewBlogRouteImport } from './routes/admin/preview/blog'
import { Route as AdminPreviewHomepageRouteImport } from './routes/admin/preview/homepage'
import { Route as AdminPreviewProjectRouteImport } from './routes/admin/preview/project'
import { Route as AdminPreviewTeamRouteImport } from './routes/admin/preview/team'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects/new'
import { Route as AdminTeamIndexRouteImport } from './routes/admin/team/index'
import { Route as AdminTeamNewRouteImport } from './routes/admin/team/new'
import { Route as AdminBlogIdEditRouteImport } from './routes/admin/blog/$id.edit'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin/projects/$id.edit'
import { Route as AdminTeamIdEditRouteImport } from './routes/admin/team/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/admin/contact',
  path: '/admin/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/admin/home',
  path: '/admin/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhotographsRoute = AdminPhotographsRouteImport.update({
  id: '/admin/photographs',
  path: '/admin/photographs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetPasswordRoute = AdminSetPasswordRouteImport.update({
  id: '/admin/set-password',
  path: '/admin/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackViewRoute = ApiTrackViewRouteImport.update({
  id: '/api/track-view',
  path: '/api/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsIndexRoute = DevelopmentsIndexRouteImport.update({
  id: '/developments/',
  path: '/developments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsSplatRoute = DevelopmentsSplatRouteImport.update({
  id: '/developments/$',
  path: '/developments/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogCategoriesRoute = AdminBlogCategoriesRouteImport.update({
  id: '/admin/blog/categories',
  path: '/admin/blog/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/admin/blog/new',
  path: '/admin/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewBlogRoute = AdminPreviewBlogRouteImport.update({
  id: '/admin/preview/blog',
  path: '/admin/preview/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewHomepageRoute = AdminPreviewHomepageRouteImport.update({
  id: '/admin/preview/homepage',
  path: '/admin/preview/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewProjectRoute = AdminPreviewProjectRouteImport.update({
  id: '/admin/preview/project',
  path: '/admin/preview/project',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewTeamRoute = AdminPreviewTeamRouteImport.update({
  id: '/admin/preview/team',
  path: '/admin/preview/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/admin/projects/new',
  path: '/admin/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/admin/team/',
  path: '/admin/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamNewRoute = AdminTeamNewRouteImport.update({
  id: '/admin/team/new',
  path: '/admin/team/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdEditRoute = AdminBlogIdEditRouteImport.update({
  id: '/admin/blog/$id/edit',
  path: '/admin/blog/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/admin/projects/$id/edit',
  path: '/admin/projects/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamIdEditRoute = AdminTeamIdEditRouteImport.update({
  id: '/admin/team/$id/edit',
  path: '/admin/team/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/photographs': typeof AdminPhotographsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developments/$': typeof DevelopmentsSplatRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/developments/': typeof DevelopmentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/preview/blog': typeof AdminPreviewBlogRoute
  '/admin/preview/homepage': typeof AdminPreviewHomepageRoute
  '/admin/preview/project': typeof AdminPreviewProjectRoute
  '/admin/preview/team': typeof AdminPreviewTeamRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/team/$id/edit': typeof AdminTeamIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/photographs': typeof AdminPhotographsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developments/$': typeof DevelopmentsSplatRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/developments': typeof DevelopmentsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/preview/blog': typeof AdminPreviewBlogRoute
  '/admin/preview/homepage': typeof AdminPreviewHomepageRoute
  '/admin/preview/project': typeof AdminPreviewProjectRoute
  '/admin/preview/team': typeof AdminPreviewTeamRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/team/$id/edit': typeof AdminTeamIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/photographs': typeof AdminPhotographsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developments/$': typeof DevelopmentsSplatRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/developments/': typeof DevelopmentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/preview/blog': typeof AdminPreviewBlogRoute
  '/admin/preview/homepage': typeof AdminPreviewHomepageRoute
  '/admin/preview/project': typeof AdminPreviewProjectRoute
  '/admin/preview/team': typeof AdminPreviewTeamRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/team/$id/edit': typeof AdminTeamIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/team'
    | '/testimonials'
    | '/admin/$'
    | '/admin/about'
    | '/admin/analytics'
    | '/admin/contact'
    | '/admin/home'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/photographs'
    | '/admin/services'
    | '/admin/set-password'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/testimonials'
    | '/admin/users'
    | '/api/track-view'
    | '/blog/$slug'
    | '/developments/$'
    | '/projects/$slug'
    | '/admin/'
    | '/blog/'
    | '/developments/'
    | '/projects/'
    | '/admin/blog/categories'
    | '/admin/blog/new'
    | '/admin/preview/blog'
    | '/admin/preview/homepage'
    | '/admin/preview/project'
    | '/admin/preview/team'
    | '/admin/projects/new'
    | '/admin/team/new'
    | '/admin/blog/'
    | '/admin/projects/'
    | '/admin/team/'
    | '/admin/blog/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/team/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/team'
    | '/testimonials'
    | '/admin/$'
    | '/admin/about'
    | '/admin/analytics'
    | '/admin/contact'
    | '/admin/home'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/photographs'
    | '/admin/services'
    | '/admin/set-password'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/testimonials'
    | '/admin/users'
    | '/api/track-view'
    | '/blog/$slug'
    | '/developments/$'
    | '/projects/$slug'
    | '/admin'
    | '/blog'
    | '/developments'
    | '/projects'
    | '/admin/blog/categories'
    | '/admin/blog/new'
    | '/admin/preview/blog'
    | '/admin/preview/homepage'
    | '/admin/preview/project'
    | '/admin/preview/team'
    | '/admin/projects/new'
    | '/admin/team/new'
    | '/admin/blog'
    | '/admin/projects'
    | '/admin/team'
    | '/admin/blog/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/team/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/team'
    | '/testimonials'
    | '/admin/$'
    | '/admin/about'
    | '/admin/analytics'
    | '/admin/contact'
    | '/admin/home'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/photographs'
    | '/admin/services'
    | '/admin/set-password'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/testimonials'
    | '/admin/users'
    | '/api/track-view'
    | '/blog/$slug'
    | '/developments/$'
    | '/projects/$slug'
    | '/admin/'
    | '/blog/'
    | '/developments/'
    | '/projects/'
    | '/admin/blog/categories'
    | '/admin/blog/new'
    | '/admin/preview/blog'
    | '/admin/preview/homepage'
    | '/admin/preview/project'
    | '/admin/preview/team'
    | '/admin/projects/new'
    | '/admin/team/new'
    | '/admin/blog/'
    | '/admin/projects/'
    | '/admin/team/'
    | '/admin/blog/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/team/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AdminSplatRoute: typeof AdminSplatRoute
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPhotographsRoute: typeof AdminPhotographsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSetPasswordRoute: typeof AdminSetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiTrackViewRoute: typeof ApiTrackViewRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DevelopmentsSplatRoute: typeof DevelopmentsSplatRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DevelopmentsIndexRoute: typeof DevelopmentsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  AdminBlogCategoriesRoute: typeof AdminBlogCategoriesRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminPreviewBlogRoute: typeof AdminPreviewBlogRoute
  AdminPreviewHomepageRoute: typeof AdminPreviewHomepageRoute
  AdminPreviewProjectRoute: typeof AdminPreviewProjectRoute
  AdminPreviewTeamRoute: typeof AdminPreviewTeamRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminTeamNewRoute: typeof AdminTeamNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
  AdminBlogIdEditRoute: typeof AdminBlogIdEditRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
  AdminTeamIdEditRoute: typeof AdminTeamIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/admin/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/photographs': {
      id: '/admin/photographs'
      path: '/admin/photographs'
      fullPath: '/admin/photographs'
      preLoaderRoute: typeof AdminPhotographsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/set-password': {
      id: '/admin/set-password'
      path: '/admin/set-password'
      fullPath: '/admin/set-password'
      preLoaderRoute: typeof AdminSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-view': {
      id: '/api/track-view'
      path: '/api/track-view'
      fullPath: '/api/track-view'
      preLoaderRoute: typeof ApiTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments/': {
      id: '/developments/'
      path: '/developments'
      fullPath: '/developments/'
      preLoaderRoute: typeof DevelopmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments/$': {
      id: '/developments/$'
      path: '/developments/$'
      fullPath: '/developments/$'
      preLoaderRoute: typeof DevelopmentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/categories': {
      id: '/admin/blog/categories'
      path: '/admin/blog/categories'
      fullPath: '/admin/blog/categories'
      preLoaderRoute: typeof AdminBlogCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preview/blog': {
      id: '/admin/preview/blog'
      path: '/admin/preview/blog'
      fullPath: '/admin/preview/blog'
      preLoaderRoute: typeof AdminPreviewBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preview/homepage': {
      id: '/admin/preview/homepage'
      path: '/admin/preview/homepage'
      fullPath: '/admin/preview/homepage'
      preLoaderRoute: typeof AdminPreviewHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preview/project': {
      id: '/admin/preview/project'
      path: '/admin/preview/project'
      fullPath: '/admin/preview/project'
      preLoaderRoute: typeof AdminPreviewProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preview/team': {
      id: '/admin/preview/team'
      path: '/admin/preview/team'
      fullPath: '/admin/preview/team'
      preLoaderRoute: typeof AdminPreviewTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/admin/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/admin/team'
      fullPath: '/admin/team/'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/new': {
      id: '/admin/team/new'
      path: '/admin/team/new'
      fullPath: '/admin/team/new'
      preLoaderRoute: typeof AdminTeamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id/edit': {
      id: '/admin/blog/$id/edit'
      path: '/admin/blog/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AdminBlogIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$id/edit': {
      id: '/admin/projects/$id/edit'
      path: '/admin/projects/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/$id/edit': {
      id: '/admin/team/$id/edit'
      path: '/admin/team/$id/edit'
      fullPath: '/admin/team/$id/edit'
      preLoaderRoute: typeof AdminTeamIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TestimonialsRoute: TestimonialsRoute,
  AdminSplatRoute: AdminSplatRoute,
  AdminAboutRoute: AdminAboutRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPhotographsRoute: AdminPhotographsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSetPasswordRoute: AdminSetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiTrackViewRoute: ApiTrackViewRoute,
  BlogSlugRoute: BlogSlugRoute,
  DevelopmentsSplatRoute: DevelopmentsSplatRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DevelopmentsIndexRoute: DevelopmentsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  AdminBlogCategoriesRoute: AdminBlogCategoriesRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminPreviewBlogRoute: AdminPreviewBlogRoute,
  AdminPreviewHomepageRoute: AdminPreviewHomepageRoute,
  AdminPreviewProjectRoute: AdminPreviewProjectRoute,
  AdminPreviewTeamRoute: AdminPreviewTeamRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminTeamNewRoute: AdminTeamNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
  AdminBlogIdEditRoute: AdminBlogIdEditRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
  AdminTeamIdEditRoute: AdminTeamIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
